"""v1 schema - all 15 tables with indexes

Revision ID: dd6550e7a397
Revises: 
Create Date: 2026-03-11 12:28:51.400680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6550e7a397'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('subindustry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('market_cap_bucket', sa.String(length=50), nullable=True),
    sa.Column('primary_exchange', sa.String(length=50), nullable=True),
    sa.Column('status_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('peer_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('multiple_basis', sa.String(length=50), nullable=True),
    sa.Column('status_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme_name', sa.String(length=255), nullable=False),
    sa.Column('theme_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_name')
    )
    op.create_table('checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checkpoint_type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_expected', sa.Date(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('linked_company_ticker', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['linked_company_ticker'], ['companies.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_peer_group_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_ticker', sa.String(length=20), nullable=False),
    sa.Column('peer_group_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['company_ticker'], ['companies.ticker'], ),
    sa.ForeignKeyConstraint(['peer_group_id'], ['peer_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_ticker', 'peer_group_id', name='uq_company_peergroup')
    )
    op.create_index(op.f('ix_company_peer_group_links_company_ticker'), 'company_peer_group_links', ['company_ticker'], unique=False)
    op.create_index(op.f('ix_company_peer_group_links_peer_group_id'), 'company_peer_group_links', ['peer_group_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.Enum('NEWS', 'TEN_K', 'TEN_Q', 'EIGHT_K', 'EARNINGS_TRANSCRIPT', 'INVESTOR_PRESENTATION', 'PRESS_RELEASE', 'POLICY_DOCUMENT', 'BROKER_REPORT', name='sourcetype'), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('source_tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', name='sourcetier'), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('primary_company_ticker', sa.String(length=20), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('hash', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['primary_company_ticker'], ['companies.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_documents_url')
    )
    op.create_index(op.f('ix_documents_hash'), 'documents', ['hash'], unique=False)
    op.create_index(op.f('ix_documents_published_at'), 'documents', ['published_at'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('claim_text_normalized', sa.Text(), nullable=False),
    sa.Column('claim_text_short', sa.Text(), nullable=True),
    sa.Column('claim_type', sa.Enum('DEMAND', 'PRICING', 'MARGIN', 'CAPACITY', 'GUIDANCE', 'REGULATION', 'COMPETITION', 'CAPITAL_ALLOCATION', 'INVENTORY', 'CUSTOMER_BEHAVIOR', 'SUPPLY_CHAIN', name='claimtype'), nullable=False),
    sa.Column('economic_channel', sa.Enum('REVENUE', 'GROSS_MARGIN', 'OPEX', 'EARNINGS', 'MULTIPLE', 'SENTIMENT', 'LIQUIDITY', 'TIMING', name='economicchannel'), nullable=False),
    sa.Column('direction', sa.Enum('POSITIVE', 'NEGATIVE', 'MIXED', 'NEUTRAL', name='direction'), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('time_horizon', sa.String(length=50), nullable=True),
    sa.Column('novelty_type', sa.Enum('NEW', 'CONFIRMING', 'CONFLICTING', 'REPETITIVE', name='noveltytype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('is_structural', sa.Boolean(), nullable=False),
    sa.Column('is_ephemeral', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_document_id'), 'claims', ['document_id'], unique=False)
    op.create_index(op.f('ix_claims_published_at'), 'claims', ['published_at'], unique=False)
    op.create_table('theses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_ticker', sa.String(length=20), nullable=False),
    sa.Column('thesis_type', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('FORMING', 'STRENGTHENING', 'STABLE', 'WEAKENING', 'BROKEN', 'ACHIEVED', 'PROBATION', name='thesisstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expiry_review_date', sa.Date(), nullable=True),
    sa.Column('expected_horizon_days', sa.Integer(), nullable=True),
    sa.Column('peer_group_current_id', sa.Integer(), nullable=True),
    sa.Column('peer_group_target_id', sa.Integer(), nullable=True),
    sa.Column('base_case_rerating', sa.Float(), nullable=True),
    sa.Column('bull_case_rerating', sa.Float(), nullable=True),
    sa.Column('bear_case_rerating', sa.Float(), nullable=True),
    sa.Column('checkpoint_next_id', sa.Integer(), nullable=True),
    sa.Column('conviction_score', sa.Float(), nullable=True),
    sa.Column('valuation_gap_pct', sa.Float(), nullable=True),
    sa.Column('downside_risk_score', sa.Float(), nullable=True),
    sa.Column('status_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_next_id'], ['checkpoints.id'], ),
    sa.ForeignKeyConstraint(['company_ticker'], ['companies.ticker'], ),
    sa.ForeignKeyConstraint(['peer_group_current_id'], ['peer_groups.id'], ),
    sa.ForeignKeyConstraint(['peer_group_target_id'], ['peer_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theses_company_ticker'), 'theses', ['company_ticker'], unique=False)
    op.create_index(op.f('ix_theses_conviction_score'), 'theses', ['conviction_score'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('primary_thesis_id', sa.Integer(), nullable=True),
    sa.Column('conviction_score', sa.Float(), nullable=True),
    sa.Column('buyable_flag', sa.Boolean(), nullable=False),
    sa.Column('zone_state', sa.Enum('BUY', 'HOLD', 'TRIM', 'FULL_EXIT', name='zonestate'), nullable=True),
    sa.Column('watch_reason', sa.Text(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('cooldown_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['primary_thesis_id'], ['theses.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['companies.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_ticker'), 'candidates', ['ticker'], unique=False)
    op.create_table('claim_company_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('company_ticker', sa.String(length=20), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['company_ticker'], ['companies.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'company_ticker', name='uq_claim_company')
    )
    op.create_index(op.f('ix_claim_company_links_claim_id'), 'claim_company_links', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_company_links_company_ticker'), 'claim_company_links', ['company_ticker'], unique=False)
    op.create_table('claim_theme_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'theme_id', name='uq_claim_theme')
    )
    op.create_index(op.f('ix_claim_theme_links_claim_id'), 'claim_theme_links', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_theme_links_theme_id'), 'claim_theme_links', ['theme_id'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('current_weight', sa.Float(), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=False),
    sa.Column('conviction_score', sa.Float(), nullable=False),
    sa.Column('zone_state', sa.Enum('BUY', 'HOLD', 'TRIM', 'FULL_EXIT', name='zonestate'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='positionstatus'), nullable=False),
    sa.Column('probation_flag', sa.Boolean(), nullable=False),
    sa.Column('cooldown_flag', sa.Boolean(), nullable=False),
    sa.Column('hold_through_earnings_allowed', sa.Boolean(), nullable=False),
    sa.Column('take_profit_zone_low', sa.Float(), nullable=True),
    sa.Column('hold_zone_low', sa.Float(), nullable=True),
    sa.Column('trim_zone_low', sa.Float(), nullable=True),
    sa.Column('full_exit_zone_low', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['companies.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_positions_thesis_id'), 'portfolio_positions', ['thesis_id'], unique=False)
    op.create_index(op.f('ix_portfolio_positions_ticker'), 'portfolio_positions', ['ticker'], unique=False)
    op.create_table('thesis_claim_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thesis_id', 'claim_id', name='uq_thesis_claim')
    )
    op.create_index(op.f('ix_thesis_claim_links_claim_id'), 'thesis_claim_links', ['claim_id'], unique=False)
    op.create_index(op.f('ix_thesis_claim_links_thesis_id'), 'thesis_claim_links', ['thesis_id'], unique=False)
    op.create_table('thesis_state_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('FORMING', 'STRENGTHENING', 'STABLE', 'WEAKENING', 'BROKEN', 'ACHIEVED', 'PROBATION', name='thesisstate'), nullable=False),
    sa.Column('conviction_score', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_state_history_thesis_id'), 'thesis_state_history', ['thesis_id'], unique=False)
    op.create_table('thesis_theme_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thesis_id', 'theme_id', name='uq_thesis_theme')
    )
    op.create_index(op.f('ix_thesis_theme_links_theme_id'), 'thesis_theme_links', ['theme_id'], unique=False)
    op.create_index(op.f('ix_thesis_theme_links_thesis_id'), 'thesis_theme_links', ['thesis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thesis_theme_links_thesis_id'), table_name='thesis_theme_links')
    op.drop_index(op.f('ix_thesis_theme_links_theme_id'), table_name='thesis_theme_links')
    op.drop_table('thesis_theme_links')
    op.drop_index(op.f('ix_thesis_state_history_thesis_id'), table_name='thesis_state_history')
    op.drop_table('thesis_state_history')
    op.drop_index(op.f('ix_thesis_claim_links_thesis_id'), table_name='thesis_claim_links')
    op.drop_index(op.f('ix_thesis_claim_links_claim_id'), table_name='thesis_claim_links')
    op.drop_table('thesis_claim_links')
    op.drop_index(op.f('ix_portfolio_positions_ticker'), table_name='portfolio_positions')
    op.drop_index(op.f('ix_portfolio_positions_thesis_id'), table_name='portfolio_positions')
    op.drop_table('portfolio_positions')
    op.drop_index(op.f('ix_claim_theme_links_theme_id'), table_name='claim_theme_links')
    op.drop_index(op.f('ix_claim_theme_links_claim_id'), table_name='claim_theme_links')
    op.drop_table('claim_theme_links')
    op.drop_index(op.f('ix_claim_company_links_company_ticker'), table_name='claim_company_links')
    op.drop_index(op.f('ix_claim_company_links_claim_id'), table_name='claim_company_links')
    op.drop_table('claim_company_links')
    op.drop_index(op.f('ix_candidates_ticker'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_theses_conviction_score'), table_name='theses')
    op.drop_index(op.f('ix_theses_company_ticker'), table_name='theses')
    op.drop_table('theses')
    op.drop_index(op.f('ix_claims_published_at'), table_name='claims')
    op.drop_index(op.f('ix_claims_document_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_documents_published_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_company_peer_group_links_peer_group_id'), table_name='company_peer_group_links')
    op.drop_index(op.f('ix_company_peer_group_links_company_ticker'), table_name='company_peer_group_links')
    op.drop_table('company_peer_group_links')
    op.drop_table('checkpoints')
    op.drop_table('themes')
    op.drop_table('peer_groups')
    op.drop_table('companies')
    # ### end Alembic commands ###
